// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: proto/protocal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComClient is the client API for Com service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComClient interface {
	MoveContainer(ctx context.Context, opts ...grpc.CallOption) (Com_MoveContainerClient, error)
	FetchShip(ctx context.Context, in *ShipAccess, opts ...grpc.CallOption) (*ShipResponse, error)
	FetchList(ctx context.Context, in *Header, opts ...grpc.CallOption) (*ShipList, error)
}

type comClient struct {
	cc grpc.ClientConnInterface
}

func NewComClient(cc grpc.ClientConnInterface) ComClient {
	return &comClient{cc}
}

func (c *comClient) MoveContainer(ctx context.Context, opts ...grpc.CallOption) (Com_MoveContainerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Com_ServiceDesc.Streams[0], "/proto.Com/MoveContainer", opts...)
	if err != nil {
		return nil, err
	}
	x := &comMoveContainerClient{stream}
	return x, nil
}

type Com_MoveContainerClient interface {
	Send(*Pack) error
	Recv() (*Pack, error)
	grpc.ClientStream
}

type comMoveContainerClient struct {
	grpc.ClientStream
}

func (x *comMoveContainerClient) Send(m *Pack) error {
	return x.ClientStream.SendMsg(m)
}

func (x *comMoveContainerClient) Recv() (*Pack, error) {
	m := new(Pack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *comClient) FetchShip(ctx context.Context, in *ShipAccess, opts ...grpc.CallOption) (*ShipResponse, error) {
	out := new(ShipResponse)
	err := c.cc.Invoke(ctx, "/proto.Com/FetchShip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comClient) FetchList(ctx context.Context, in *Header, opts ...grpc.CallOption) (*ShipList, error) {
	out := new(ShipList)
	err := c.cc.Invoke(ctx, "/proto.Com/FetchList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComServer is the server API for Com service.
// All implementations must embed UnimplementedComServer
// for forward compatibility
type ComServer interface {
	MoveContainer(Com_MoveContainerServer) error
	FetchShip(context.Context, *ShipAccess) (*ShipResponse, error)
	FetchList(context.Context, *Header) (*ShipList, error)
	mustEmbedUnimplementedComServer()
}

// UnimplementedComServer must be embedded to have forward compatible implementations.
type UnimplementedComServer struct {
}

func (UnimplementedComServer) MoveContainer(Com_MoveContainerServer) error {
	return status.Errorf(codes.Unimplemented, "method MoveContainer not implemented")
}
func (UnimplementedComServer) FetchShip(context.Context, *ShipAccess) (*ShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchShip not implemented")
}
func (UnimplementedComServer) FetchList(context.Context, *Header) (*ShipList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchList not implemented")
}
func (UnimplementedComServer) mustEmbedUnimplementedComServer() {}

// UnsafeComServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComServer will
// result in compilation errors.
type UnsafeComServer interface {
	mustEmbedUnimplementedComServer()
}

func RegisterComServer(s grpc.ServiceRegistrar, srv ComServer) {
	s.RegisterService(&Com_ServiceDesc, srv)
}

func _Com_MoveContainer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComServer).MoveContainer(&comMoveContainerServer{stream})
}

type Com_MoveContainerServer interface {
	Send(*Pack) error
	Recv() (*Pack, error)
	grpc.ServerStream
}

type comMoveContainerServer struct {
	grpc.ServerStream
}

func (x *comMoveContainerServer) Send(m *Pack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *comMoveContainerServer) Recv() (*Pack, error) {
	m := new(Pack)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Com_FetchShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComServer).FetchShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Com/FetchShip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComServer).FetchShip(ctx, req.(*ShipAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _Com_FetchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Header)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComServer).FetchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Com/FetchList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComServer).FetchList(ctx, req.(*Header))
	}
	return interceptor(ctx, in, info, handler)
}

// Com_ServiceDesc is the grpc.ServiceDesc for Com service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Com_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Com",
	HandlerType: (*ComServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchShip",
			Handler:    _Com_FetchShip_Handler,
		},
		{
			MethodName: "FetchList",
			Handler:    _Com_FetchList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MoveContainer",
			Handler:       _Com_MoveContainer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/protocal.proto",
}
