// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/protocal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	AtTime string `protobuf:"bytes,3,opt,name=atTime,proto3" json:"atTime,omitempty"`
	By     string `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
}

func (x *Detail) Reset() {
	*x = Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{1}
}

func (x *Detail) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Detail) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Detail) GetAtTime() string {
	if x != nil {
		return x.AtTime
	}
	return ""
}

func (x *Detail) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Place    int32                  `protobuf:"varint,3,opt,name=place,proto3" json:"place,omitempty"`
	Name     string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NewPlace int32                  `protobuf:"varint,5,opt,name=new_place,json=newPlace,proto3" json:"new_place,omitempty"`
	Detail   *Detail                `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Container) GetPlace() int32 {
	if x != nil {
		return x.Place
	}
	return 0
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetNewPlace() int32 {
	if x != nil {
		return x.NewPlace
	}
	return 0
}

func (x *Container) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ContainerSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key    int32   `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Place  int32   `protobuf:"varint,3,opt,name=place,proto3" json:"place,omitempty"`
	Name   string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Detail *Detail `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ContainerSet) Reset() {
	*x = ContainerSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSet) ProtoMessage() {}

func (x *ContainerSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSet.ProtoReflect.Descriptor instead.
func (*ContainerSet) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerSet) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ContainerSet) GetPlace() int32 {
	if x != nil {
		return x.Place
	}
	return 0
}

func (x *ContainerSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSet) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Pack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Container `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Err  string       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Swap bool         `protobuf:"varint,3,opt,name=swap,proto3" json:"swap,omitempty"`
}

func (x *Pack) Reset() {
	*x = Pack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{4}
}

func (x *Pack) GetList() []*Container {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *Pack) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Pack) GetSwap() bool {
	if x != nil {
		return x.Swap
	}
	return false
}

type ShipAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipName string  `protobuf:"bytes,1,opt,name=ship_name,json=shipName,proto3" json:"ship_name,omitempty"`
	ManId    string  `protobuf:"bytes,2,opt,name=man_id,json=manId,proto3" json:"man_id,omitempty"`
	Floor    int32   `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	Head     *Header `protobuf:"bytes,5,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *ShipAccess) Reset() {
	*x = ShipAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipAccess) ProtoMessage() {}

func (x *ShipAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipAccess.ProtoReflect.Descriptor instead.
func (*ShipAccess) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{5}
}

func (x *ShipAccess) GetShipName() string {
	if x != nil {
		return x.ShipName
	}
	return ""
}

func (x *ShipAccess) GetManId() string {
	if x != nil {
		return x.ManId
	}
	return ""
}

func (x *ShipAccess) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *ShipAccess) GetHead() *Header {
	if x != nil {
		return x.Head
	}
	return nil
}

type ShipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size          int32        `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Err           string       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Head          *Header      `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	ContainerList []*Container `protobuf:"bytes,4,rep,name=container_list,json=containerList,proto3" json:"container_list,omitempty"`
}

func (x *ShipResponse) Reset() {
	*x = ShipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipResponse) ProtoMessage() {}

func (x *ShipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipResponse.ProtoReflect.Descriptor instead.
func (*ShipResponse) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{6}
}

func (x *ShipResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShipResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *ShipResponse) GetHead() *Header {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *ShipResponse) GetContainerList() []*Container {
	if x != nil {
		return x.ContainerList
	}
	return nil
}

type ShipList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ContainerSet `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Log  []string        `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
}

func (x *ShipList) Reset() {
	*x = ShipList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipList) ProtoMessage() {}

func (x *ShipList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipList.ProtoReflect.Descriptor instead.
func (*ShipList) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{7}
}

func (x *ShipList) GetList() []*ContainerSet {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ShipList) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

type Ship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Placed  int32                  `protobuf:"varint,2,opt,name=placed,proto3" json:"placed,omitempty"`
	Iden    string                 `protobuf:"bytes,3,opt,name=Iden,proto3" json:"Iden,omitempty"`
	Key     int32                  `protobuf:"varint,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Detail  *Detail                `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	InTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=inTime,proto3" json:"inTime,omitempty"`
	OutTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=outTime,proto3" json:"outTime,omitempty"`
	Length  uint32                 `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *Ship) Reset() {
	*x = Ship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ship) ProtoMessage() {}

func (x *Ship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ship.ProtoReflect.Descriptor instead.
func (*Ship) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{8}
}

func (x *Ship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ship) GetPlaced() int32 {
	if x != nil {
		return x.Placed
	}
	return 0
}

func (x *Ship) GetIden() string {
	if x != nil {
		return x.Iden
	}
	return ""
}

func (x *Ship) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Ship) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Ship) GetInTime() *timestamppb.Timestamp {
	if x != nil {
		return x.InTime
	}
	return nil
}

func (x *Ship) GetOutTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OutTime
	}
	return nil
}

func (x *Ship) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Doc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No           int32    `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Length       uint32   `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BoarderRight int32    `protobuf:"varint,4,opt,name=boarderRight,proto3" json:"boarderRight,omitempty"`
	ShipList     []string `protobuf:"bytes,5,rep,name=shipList,proto3" json:"shipList,omitempty"`
}

func (x *Doc) Reset() {
	*x = Doc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{9}
}

func (x *Doc) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Doc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Doc) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Doc) GetBoarderRight() int32 {
	if x != nil {
		return x.BoarderRight
	}
	return 0
}

func (x *Doc) GetShipList() []string {
	if x != nil {
		return x.ShipList
	}
	return nil
}

type Docks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ships []*Ship `protobuf:"bytes,1,rep,name=ships,proto3" json:"ships,omitempty"`
	Docks []*Doc  `protobuf:"bytes,2,rep,name=docks,proto3" json:"docks,omitempty"`
}

func (x *Docks) Reset() {
	*x = Docks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Docks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docks) ProtoMessage() {}

func (x *Docks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docks.ProtoReflect.Descriptor instead.
func (*Docks) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{10}
}

func (x *Docks) GetShips() []*Ship {
	if x != nil {
		return x.Ships
	}
	return nil
}

func (x *Docks) GetDocks() []*Doc {
	if x != nil {
		return x.Docks
	}
	return nil
}

type PlaceShip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipList   []*PlaceShip_ShipList `protobuf:"bytes,1,rep,name=shipList,proto3" json:"shipList,omitempty"`
	Ship       *Ship                 `protobuf:"bytes,2,opt,name=ship,proto3" json:"ship,omitempty"`
	ChangeTime bool                  `protobuf:"varint,3,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
}

func (x *PlaceShip) Reset() {
	*x = PlaceShip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceShip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceShip) ProtoMessage() {}

func (x *PlaceShip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceShip.ProtoReflect.Descriptor instead.
func (*PlaceShip) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{11}
}

func (x *PlaceShip) GetShipList() []*PlaceShip_ShipList {
	if x != nil {
		return x.ShipList
	}
	return nil
}

func (x *PlaceShip) GetShip() *Ship {
	if x != nil {
		return x.Ship
	}
	return nil
}

func (x *PlaceShip) GetChangeTime() bool {
	if x != nil {
		return x.ChangeTime
	}
	return false
}

type PlaceShip_ShipList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PlaceShip_ShipList) Reset() {
	*x = PlaceShip_ShipList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceShip_ShipList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceShip_ShipList) ProtoMessage() {}

func (x *PlaceShip_ShipList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceShip_ShipList.ProtoReflect.Descriptor instead.
func (*PlaceShip_ShipList) Descriptor() ([]byte, []int) {
	return file_proto_protocal_proto_rawDescGZIP(), []int{11, 0}
}

func (x *PlaceShip_ShipList) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_protocal_proto protoreflect.FileDescriptor

var file_proto_protocal_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x62, 0x79, 0x22, 0xb9, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x65, 0x77, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x81, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x22, 0x52, 0x0a, 0x04, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x77, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x73, 0x77, 0x61, 0x70, 0x22, 0x79, 0x0a, 0x0a, 0x53, 0x68, 0x69, 0x70,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c,
	0x6f, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x12, 0x21, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x65,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x37, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x08, 0x53, 0x68, 0x69, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x81, 0x02,
	0x0a, 0x04, 0x53, 0x68, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x64, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x49, 0x64, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x32, 0x0a, 0x06, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x22, 0x81, 0x01, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x69,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x69,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x05, 0x44, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x21,
	0x0a, 0x05, 0x73, 0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x05, 0x73, 0x68, 0x69, 0x70,
	0x73, 0x12, 0x20, 0x0a, 0x05, 0x64, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x05, 0x64, 0x6f,
	0x63, 0x6b, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68, 0x69,
	0x70, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x53, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08,
	0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x68, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x68, 0x69, 0x70, 0x52, 0x04, 0x73, 0x68, 0x69, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x1e, 0x0a, 0x08, 0x53, 0x68, 0x69,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xf5, 0x01, 0x0a, 0x03, 0x43, 0x6f,
	0x6d, 0x12, 0x2d, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x1a,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x33, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x68, 0x69, 0x70, 0x12, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x6f, 0x63, 0x6b, 0x73,
	0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x32, 0x0a,
	0x08, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x68, 0x69, 0x70, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68, 0x69, 0x70, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68, 0x69, 0x70, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x48, 0x61, 0x69, 0x48, 0x61, 0x72, 0x74, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x64, 0x6f, 0x63, 0x6b,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_protocal_proto_rawDescOnce sync.Once
	file_proto_protocal_proto_rawDescData = file_proto_protocal_proto_rawDesc
)

func file_proto_protocal_proto_rawDescGZIP() []byte {
	file_proto_protocal_proto_rawDescOnce.Do(func() {
		file_proto_protocal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protocal_proto_rawDescData)
	})
	return file_proto_protocal_proto_rawDescData
}

var file_proto_protocal_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_protocal_proto_goTypes = []interface{}{
	(*Header)(nil),                // 0: proto.Header
	(*Detail)(nil),                // 1: proto.Detail
	(*Container)(nil),             // 2: proto.Container
	(*ContainerSet)(nil),          // 3: proto.ContainerSet
	(*Pack)(nil),                  // 4: proto.Pack
	(*ShipAccess)(nil),            // 5: proto.ShipAccess
	(*ShipResponse)(nil),          // 6: proto.ShipResponse
	(*ShipList)(nil),              // 7: proto.ShipList
	(*Ship)(nil),                  // 8: proto.Ship
	(*Doc)(nil),                   // 9: proto.Doc
	(*Docks)(nil),                 // 10: proto.Docks
	(*PlaceShip)(nil),             // 11: proto.PlaceShip
	(*PlaceShip_ShipList)(nil),    // 12: proto.PlaceShip.ShipList
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proto_protocal_proto_depIdxs = []int32{
	13, // 0: proto.Header.time:type_name -> google.protobuf.Timestamp
	13, // 1: proto.Container.time:type_name -> google.protobuf.Timestamp
	1,  // 2: proto.Container.detail:type_name -> proto.Detail
	1,  // 3: proto.ContainerSet.detail:type_name -> proto.Detail
	2,  // 4: proto.Pack.list:type_name -> proto.Container
	0,  // 5: proto.ShipAccess.head:type_name -> proto.Header
	0,  // 6: proto.ShipResponse.head:type_name -> proto.Header
	2,  // 7: proto.ShipResponse.container_list:type_name -> proto.Container
	3,  // 8: proto.ShipList.list:type_name -> proto.ContainerSet
	1,  // 9: proto.Ship.detail:type_name -> proto.Detail
	13, // 10: proto.Ship.inTime:type_name -> google.protobuf.Timestamp
	13, // 11: proto.Ship.outTime:type_name -> google.protobuf.Timestamp
	8,  // 12: proto.Docks.ships:type_name -> proto.Ship
	9,  // 13: proto.Docks.docks:type_name -> proto.Doc
	12, // 14: proto.PlaceShip.shipList:type_name -> proto.PlaceShip.ShipList
	8,  // 15: proto.PlaceShip.ship:type_name -> proto.Ship
	4,  // 16: proto.Com.MoveContainer:input_type -> proto.Pack
	5,  // 17: proto.Com.FetchShip:input_type -> proto.ShipAccess
	0,  // 18: proto.Com.FetchList:input_type -> proto.Header
	0,  // 19: proto.Com.FetchDocks:input_type -> proto.Header
	11, // 20: proto.Com.MoveShip:input_type -> proto.PlaceShip
	4,  // 21: proto.Com.MoveContainer:output_type -> proto.Pack
	6,  // 22: proto.Com.FetchShip:output_type -> proto.ShipResponse
	7,  // 23: proto.Com.FetchList:output_type -> proto.ShipList
	10, // 24: proto.Com.FetchDocks:output_type -> proto.Docks
	11, // 25: proto.Com.MoveShip:output_type -> proto.PlaceShip
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_protocal_proto_init() }
func file_proto_protocal_proto_init() {
	if File_proto_protocal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protocal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Docks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceShip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceShip_ShipList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protocal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_protocal_proto_goTypes,
		DependencyIndexes: file_proto_protocal_proto_depIdxs,
		MessageInfos:      file_proto_protocal_proto_msgTypes,
	}.Build()
	File_proto_protocal_proto = out.File
	file_proto_protocal_proto_rawDesc = nil
	file_proto_protocal_proto_goTypes = nil
	file_proto_protocal_proto_depIdxs = nil
}
